config/routes.rb
Kindletrend::Application.routes.draw do
    devise_for :users, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
    end

  resources :categories

  resources :ebooks

  get 'rollup', to: 'categories#rollup'
  get 'categories/:category/analytics/', to: 'categories#analytics'
  get 'targets', to: 'categories#targets'
  get 'estimations', to: 'welcome#calcs'
  get 'mission', to: 'welcome#mission'
  get 'categories/:category_id/takeoff', to: "categories#takeoff"
  get 'categories/:keywords/amazon_suggest', to: "categories#amazon_suggest"
  
  get 'accounts/subscription', to: "accounts#subscription", as: "subscribe"
  post 'accounts/process_subscription', to: "accounts#process_subscription"
  match 'jvzoo_instant_notification', to: "accounts#jvzoo_instant_notification", via: [:options]
  post 'jvzoo_instant_notification', to: "accounts#jvzoo_instant_notification"
  post 'click2sell_instant_notification', to: "accounts#click2sell_instant_notification"
  post 'spawn_user', to: "accounts#spawn_user"
  delete 'accounts/cancel_subscription', to: "accounts#cancel_subscription", as: "cancel_subscription"
  match 'accounts/partner_integration', to: "accounts#partner_integration", via: [:options]
  post 'accounts/partner_integration', to: "accounts#partner_integration"
  match 'accounts/partner_gen_integration' => "accounts#partner_gen_password", via: [:options]
  post 'accounts/partner_gen_integration' => "accounts#partner_gen_password"  

  match 'accounts/zaxaa_integration', to: "accounts#zaxaa_zpn", via: [:options]
  post 'accounts/zaxaa_integration', to: "accounts#zaxaa_zpn"

  match 'accounts/zaxaa', to: "accounts#zaxaa", via: [:options]
  post 'accounts/zaxaa', to: "accounts#zaxaa"
  get 'accounts/zaxaa', to: "accounts#zaxaa"
  match 'accounts/zaxaa', to: 'accounts#zaxaa', :constraints => { :protocol => 'http' }, :via => :get
  post 'verify/coupon', to: "accounts#verify_coupon"

  get 'partner/login', to: "accounts#whitelabel_login"
  post 'partner/user/login', to: "accounts#whitelabel_create_user_session"
  delete 'partner/logout', to: "accounts#whitelabel_logout"
  get 'partner/edit', to: "accounts#whitelabel_edit_account"
  post 'partner/user/update', to: "accounts#whitelabel_update_account"

  get 'retrieval_assignment', to: "parser#assign_category"
  get 'category_assignment', to: "parser#assign_cat_id"
  match 'data_consumer', to: "parser#parse_page", via: [:options]
  post 'data_consumer', to: "parser#parse_page"
  match 'custom_crawl', to: "parser#custom_crawl", via: [:options]
  post 'custom_crawl', to: "parser#custom_crawl"

  get 'oneclick_admin', to: "oneclick_admin#mapper"
  post 'parse_form', to: "oneclick_admin#parse_form"
  post 'save_form_data', to: "oneclick_admin#save_form_data"

  get "promotions/resources", to: "promotions#resources"

  get "widgets/partner_sign_up", to: "widgets#partner_sign_up"
  get "widgets/partner_iframe", to: "widgets#partner_iframe"
  get "widgets/partner_resize_injection", to: "widgets#partner_resize_injection"

  get 'control_panel/system_admin', to: "control_panel#system_admin"
  get 'control_panel/users_report', to: "control_panel#users_report"
  get 'control_panel/watches_admin', to: "control_panel#watches_admin", as: "watches_admin"
  post 'control_panel/watches_update', to: "control_panel#watches_update"
  get 'whitelabel/admin', to: "control_panel#white_label_admin"
  post 'whitelabel/update', to: "control_panel#white_label_update"
  post 'control_panel/user_update', to: "control_panel#user_update"

  root to: 'welcome#index'

end

app/views/partials/_flash_messages.html.erb
<% flash.each do |type, message| %>
<div class="alert <%= bootstrap_class_for(type) %> fade in">
<button class="close" data-dismiss="alert">×</button>
<%= message %>
</div>
<% end %>

app/views/partials/_footer.html.erb
<div id="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-5">
				<p class="text-muted">Copyright &copy; 2014. All rights reserved.</p>
			</div>
			<div class="col-md-7">
				<p class="text-muted pull-right" style="text-align: right;">
					<%= link_to "Terms of Service", "http://www.kindletrend.com/terms-and-conditions", :target => "blank" %> &bull; 
					<%= link_to "Helpdesk", "http://www.kindletrend.com/helpdesk", :target => "blank" %> &bull; 
					<%= link_to "Contact Us", "http://www.kindletrend.com/contact-us", :target => "blank" %> &bull;
					<%= link_to "Guarantee", "http://www.kindletrend.com/refund-policy/" %> &bull;
					<%= link_to "Privacy", "http://www.kindletrend.com/privacy-policy/" %> &bull;
					<%= link_to "The Kindle Trend Mission", mission_path %><!-- &bull; -->
					<%#= link_to "FAQ", "#" %>
				</p>
			</div>
		</div>
		</div>
</div>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="brand" href="#"><%= image_tag "logo.png", :height => 75 %></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <% if user_signed_in? %>
    <ul class="nav navbar-nav">
      <li><%= link_to "How to use #{@friendly_product}", root_path %></li>
      <li><%= link_to "Category Summaries", rollup_path %></li>
      <li><%= link_to "Easy Targets", targets_path %></li>
      <li><%= link_to "Category Tree", categories_path %></li>
      <li><a href="/app/promotions/resources">Resources</a></li>
      <li><a href="https://chrome.google.com/webstore/detail/kindle-trend-chrome/akmahfgfdgchjcoihknfkjhnollokgmd" target="_BLANK">Google Chrome Extension</a></li>
      <!--sup style="color: red;"> * NEW</sup-->
      <%#= link_to "Resources * NEW", promotions_resources_path %>
      <!--li><%#= link_to "Promoting Your Book", "#" %></li-->
      <% if current_user.role == 'sys_admin' || current_user.role == 'jv_admin' || current_user.role == 'partner_admin' %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Control Panel <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% if current_user.role == 'sys_admin' || current_user.role == 'jv_admin' %><li><%= link_to "Joint Venture Reports", control_panel_users_report_path %></li><% end %>
          <% if current_user.role == 'partner_admin' %><li><%= link_to "Partner Reports", control_panel_users_report_path %></li><% end %>
          <% if current_user.role == 'partner_admin' && current_user.account.partner.partner_type_id == 2 %><li><%= link_to "White Label Admin", whitelabel_admin_path %></li><% end %>
          <% if current_user.role == "sys_admin" %>
            <li class="divider"></li>
            <li><%= link_to "Watches Admin", watches_admin_path %></li>
            <li><%= link_to "Sidekiq Monitor", "/app/automation_queue", target: "BLANK" %></li>
            <li><%= link_to "PHPMyAdmin", "/phpmyadmin", target: "BLANK" %></li>
          <% end %>
          <!--li><a href="#">Account Settings</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li class="divider"></li>
          <li><a href="#">One more separated link</a></li-->
        </ul>
      </li>
      <% end %>
    </ul>
    <% end %>
    <div id="user_nav" class="navbar-right" style="margin-top: 15px;">
      <% if user_signed_in? %>
        <strong><%= current_user.email %></strong>
        <%= link_to 'Edit profile', edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%#= link_to "Sign up", new_user_registration_path %>
        <%= link_to "Sign up", subscribe_path %> |
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    </div>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/partials/_special_offers.html.erb
<% offers = SpecialOffer.where(active: true) %>
<% unless offers.empty? %>
	<% offers.each do |o| %>
	<div class="alert alert-success fade in" style="position: relative;">
		<button class="close" data-dismiss="alert">×</button>
		<h1><%= o.title %></h1>
		<% unless o.img.blank? %>
			<div class="pull-left">
				<%= image_tag o.img, :height => 100, :style => "margin-right: 15px; border: 1px solid darkgreen;" %>
			</div>
		<% end %>
		<div>
			<p><%= o.desc %></p>
			<div style="padding-bottom: 25px;"></div>
			<%= link_to o.url, :target => "_BLANK" do %>
			<button class="btn btn-success btn-lg pull-right"><%= o.button_text.blank? ? "Learn More" : "#{o.button_text}" %></button>
			<% end %>
		</div>
		<div style="clear: both;"></div>
	</div>
	<% end %>
<% end %>

app/views/partials/_words.html.erb
<% ######################################
#  Can this be extracted and pushed back 
#  into a controller somewhere?

    bestseller = Bestseller.find_by(category_id: params[:category_id])

    if bestseller.blank?
      puts bestseller.id
    end

#  Get title keywords.
    titles = keywords(bestseller.id, "title")
    @titlewords = titles.sort_by {|key, value| -value}
#   End title keywords.

#   Get desc keywords.
    descs = keywords(bestseller.id, "desc")
    @descwords = descs.sort_by {|key, value| -value}
#   End desc keywords.
%>

<div class="col-md-4">
  <div class="panel panel-default">
    <div class="panel-heading"><span class="panel-title lead">Common Words in Titles</span></div>
    <div class="panel-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th class="bold">Word</th>
            <th>Count</th>
          </tr>
        </thead>
        <% @titlewords.each do |t| %>
          <% if t[1] > 3 %>
          <tr>
            <td><%= t[0] %></td>
            <td><%= t[1] %></td>
          </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>
</div>

<div id="common_words" class="col-md-3">
<div class="panel panel-default">
  <div class="panel-heading"><span class="panel-title lead">Common words in description</span></div>
  <div class="panel-body">
    <table class="table table-striped">
      <tr>
        <thead>
          <tr>
            <th>Word</th>
            <th>Count</th>
          </tr>
        </thead>
      </tr>
      <% @descwords.each do |d| %>
        <% if d[1] > 24 %>
        <tr>
          <td><%= d[0] %></td>
          <td><%= d[1] %></td>
        </tr>
        <% end %>
      <% end %>
    </table>
    </div>
  </div>
</div>

app/views/partials/jon_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Kindle Store Analyzer</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="<%= "active" if params[:controller] == "dashboard" %>"><%= link_to "Dashboard", "#" %><!--a href="dashboard.html">Dashboard</a--></li>
    	<li class="<%= "active" if params[:controller] == "intelligence" %>"><%= link_to "Intelligence", analytics_intelligence_index_path %><!--a href="intelligence.html">Intelligence</a--></li>
    	<li class="<%= "active" if params[:controller] == "watches" %>"><%= link_to "Watches", "#" %><!--a href="watches.html">Watches</a--></li>
    	<li class="<%= "active" if params[:controller] == "promotions" %>"><%= link_to "Promotions", "#" %><!--a href="promotions.html">Promotions</a--></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>