config/routes.rb
Kindletrend::Application.routes.draw do
    devise_for :users, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
    end

  resources :categories

  resources :ebooks

  get 'rollup', to: 'categories#rollup'
  get 'categories/:category/analytics/', to: 'categories#analytics'
  get 'targets', to: 'categories#targets'
  get 'estimations', to: 'welcome#calcs'
  get 'mission', to: 'welcome#mission'
  get 'categories/:category_id/takeoff', to: "categories#takeoff"
  get 'categories/:keywords/amazon_suggest', to: "categories#amazon_suggest"
  
  get 'accounts/subscription', to: "accounts#subscription", as: "subscribe"
  post 'accounts/process_subscription', to: "accounts#process_subscription"
  match 'jvzoo_instant_notification', to: "accounts#jvzoo_instant_notification", via: [:options]
  post 'jvzoo_instant_notification', to: "accounts#jvzoo_instant_notification"
  post 'click2sell_instant_notification', to: "accounts#click2sell_instant_notification"
  post 'spawn_user', to: "accounts#spawn_user"
  delete 'accounts/cancel_subscription', to: "accounts#cancel_subscription", as: "cancel_subscription"
  match 'accounts/partner_integration', to: "accounts#partner_integration", via: [:options]
  post 'accounts/partner_integration', to: "accounts#partner_integration"
  match 'accounts/partner_gen_integration' => "accounts#partner_gen_password", via: [:options]
  post 'accounts/partner_gen_integration' => "accounts#partner_gen_password"  

  match 'accounts/zaxaa_integration', to: "accounts#zaxaa_zpn", via: [:options]
  post 'accounts/zaxaa_integration', to: "accounts#zaxaa_zpn"

  match 'accounts/zaxaa', to: "accounts#zaxaa", via: [:options]
  post 'accounts/zaxaa', to: "accounts#zaxaa"
  get 'accounts/zaxaa', to: "accounts#zaxaa"
  match 'accounts/zaxaa', to: 'accounts#zaxaa', :constraints => { :protocol => 'http' }, :via => :get
  post 'verify/coupon', to: "accounts#verify_coupon"

  get 'partner/login', to: "accounts#whitelabel_login"
  post 'partner/user/login', to: "accounts#whitelabel_create_user_session"
  delete 'partner/logout', to: "accounts#whitelabel_logout"
  get 'partner/edit', to: "accounts#whitelabel_edit_account"
  post 'partner/user/update', to: "accounts#whitelabel_update_account"

  get 'retrieval_assignment', to: "parser#assign_category"
  get 'category_assignment', to: "parser#assign_cat_id"
  match 'data_consumer', to: "parser#parse_page", via: [:options]
  post 'data_consumer', to: "parser#parse_page"
  match 'custom_crawl', to: "parser#custom_crawl", via: [:options]
  post 'custom_crawl', to: "parser#custom_crawl"

  get 'oneclick_admin', to: "oneclick_admin#mapper"
  post 'parse_form', to: "oneclick_admin#parse_form"
  post 'save_form_data', to: "oneclick_admin#save_form_data"

  get "promotions/resources", to: "promotions#resources"

  get "widgets/partner_sign_up", to: "widgets#partner_sign_up"
  get "widgets/partner_iframe", to: "widgets#partner_iframe"
  get "widgets/partner_resize_injection", to: "widgets#partner_resize_injection"

  get 'control_panel/system_admin', to: "control_panel#system_admin"
  get 'control_panel/users_report', to: "control_panel#users_report"
  get 'control_panel/watches_admin', to: "control_panel#watches_admin", as: "watches_admin"
  post 'control_panel/watches_update', to: "control_panel#watches_update"
  get 'whitelabel/admin', to: "control_panel#white_label_admin"
  post 'whitelabel/update', to: "control_panel#white_label_update"
  post 'control_panel/user_update', to: "control_panel#user_update"

  root to: 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kindle Store Analytics on Steroids! >> <%= @friendly_product %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%#= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag "application", media: "all" %>
  <%#= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render :partial => "partials/nav" %>
	<div class="container" style="padding: 0 15px;">
		<%= render partial: "partials/flash_messages", flash: flash %>
		<%= yield %>
	</div>
	<%= render :partial => "partials/footer" %>
</body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag "application", media: "all" %>
  <% if current_user.present? && current_user.account.present? && current_user.account.partner.present? && current_user.account.partner.app_style != nil %>
  <%= stylesheet_link_tag "bootstrap.#{current_user.account.partner.app_style}.min" %>
  <style>
    /*@font-face {
      font-family: 'Glyphicons';
      src:url('/assets/fonts/glyphicons-halflings-regular.eot');
      src:url('/assets/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'),
        url('/assets/fonts/glyphicons-halflings-regular.svg#glyphicons-halflings-regular') format('svg'),
        url('/assets/fonts/glyphicons-halflings-regular.woff') format('woff'),
        url('/assets/fonts/glyphicons-halflings-regular.ttf') format('truetype');
      font-weight: normal;
      font-style: normal;
    }*/
  </style>
  <% end %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to "How to use #{@friendly_product}", root_path %></li>
        <li><%= link_to "Category Summaries", rollup_path %></li>
        <li><%= link_to "Easy Targets", targets_path %></li>
        <li><%= link_to "Category Tree", categories_path %></li>
        <li><a href="/app/promotions/resources">Resources</a></li>
        <!--sup style="color: red;"> * NEW</sup-->
        <%#= link_to "Resources * NEW", promotions_resources_path %>
        <!--li><%#= link_to "Promoting Your Book", "#" %></li-->
        <% if current_user.role == 'sys_admin' || current_user.role == 'jv_admin' || current_user.role == 'partner_admin' %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Control Panel <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% if current_user.role == 'sys_admin' || current_user.role == 'jv_admin' %><li><%= link_to "Joint Venture Reports", control_panel_users_report_path %></li><% end %>
            <% if current_user.role == 'partner_admin' %><li><%= link_to "Partner Reports", control_panel_users_report_path %></li><% end %>
            <% if current_user.role == 'partner_admin' && current_user.account.partner.partner_type_id == 2 %><li><%= link_to "White Label Admin", whitelabel_admin_path %></li><% end %>
            <% if current_user.role == "sys_admin" %>
              <li class="divider"></li>
              <li><%= link_to "Watches Admin", watches_admin_path %></li>
              <li><%= link_to "Sidekiq Monitor", "/app/automation_queue", target: "BLANK" %></li>
              <li><%= link_to "PHPMyAdmin", "/phpmyadmin", target: "BLANK" %></li>
            <% end %>
            <!--li><a href="#">Account Settings</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li-->
          </ul>
        </li>
        <% end %>
      </ul>
      <% end %>
      <div id="user_nav" class="navbar-right" style="margin-top: 15px;">
        <% if user_signed_in? %>
          <strong><%= current_user.email %></strong>
          <%= link_to 'Edit profile', partner_edit_path %> |
          <%= link_to "Logout", partner_logout_path, method: :delete %>
        <% end %>
      </div>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container" style="padding: 0 15px;">
		<%= render partial: "partials/flash_messages", flash: flash %>
		<%= yield %>
	</div>
  <%#= javascript_include_tag "iframeResizer.contentWindow.min" %>
  <script src="/app/assets/iframeResizer.contentWindow.min.js"></script>
</body>
</html>