config/routes.rb
Kindletrend::Application.routes.draw do
    devise_for :users, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
    end

  resources :categories

  resources :ebooks

  get 'rollup', to: 'categories#rollup'
  get 'categories/:category/analytics/', to: 'categories#analytics'
  get 'targets', to: 'categories#targets'
  get 'estimations', to: 'welcome#calcs'
  get 'mission', to: 'welcome#mission'
  get 'categories/:category_id/takeoff', to: "categories#takeoff"
  get 'categories/:keywords/amazon_suggest', to: "categories#amazon_suggest"
  
  get 'accounts/subscription', to: "accounts#subscription", as: "subscribe"
  post 'accounts/process_subscription', to: "accounts#process_subscription"
  match 'jvzoo_instant_notification', to: "accounts#jvzoo_instant_notification", via: [:options]
  post 'jvzoo_instant_notification', to: "accounts#jvzoo_instant_notification"
  post 'click2sell_instant_notification', to: "accounts#click2sell_instant_notification"
  post 'spawn_user', to: "accounts#spawn_user"
  delete 'accounts/cancel_subscription', to: "accounts#cancel_subscription", as: "cancel_subscription"
  match 'accounts/partner_integration', to: "accounts#partner_integration", via: [:options]
  post 'accounts/partner_integration', to: "accounts#partner_integration"
  match 'accounts/partner_gen_integration' => "accounts#partner_gen_password", via: [:options]
  post 'accounts/partner_gen_integration' => "accounts#partner_gen_password"  

  match 'accounts/zaxaa_integration', to: "accounts#zaxaa_zpn", via: [:options]
  post 'accounts/zaxaa_integration', to: "accounts#zaxaa_zpn"

  match 'accounts/zaxaa', to: "accounts#zaxaa", via: [:options]
  post 'accounts/zaxaa', to: "accounts#zaxaa"
  get 'accounts/zaxaa', to: "accounts#zaxaa"
  match 'accounts/zaxaa', to: 'accounts#zaxaa', :constraints => { :protocol => 'http' }, :via => :get
  post 'verify/coupon', to: "accounts#verify_coupon"

  get 'partner/login', to: "accounts#whitelabel_login"
  post 'partner/user/login', to: "accounts#whitelabel_create_user_session"
  delete 'partner/logout', to: "accounts#whitelabel_logout"
  get 'partner/edit', to: "accounts#whitelabel_edit_account"
  post 'partner/user/update', to: "accounts#whitelabel_update_account"

  get 'retrieval_assignment', to: "parser#assign_category"
  get 'category_assignment', to: "parser#assign_cat_id"
  match 'data_consumer', to: "parser#parse_page", via: [:options]
  post 'data_consumer', to: "parser#parse_page"
  match 'custom_crawl', to: "parser#custom_crawl", via: [:options]
  post 'custom_crawl', to: "parser#custom_crawl"

  get 'oneclick_admin', to: "oneclick_admin#mapper"
  post 'parse_form', to: "oneclick_admin#parse_form"
  post 'save_form_data', to: "oneclick_admin#save_form_data"

  get "promotions/resources", to: "promotions#resources"

  get "widgets/partner_sign_up", to: "widgets#partner_sign_up"
  get "widgets/partner_iframe", to: "widgets#partner_iframe"
  get "widgets/partner_resize_injection", to: "widgets#partner_resize_injection"

  get 'control_panel/system_admin', to: "control_panel#system_admin"
  get 'control_panel/users_report', to: "control_panel#users_report"
  get 'control_panel/watches_admin', to: "control_panel#watches_admin", as: "watches_admin"
  post 'control_panel/watches_update', to: "control_panel#watches_update"
  get 'whitelabel/admin', to: "control_panel#white_label_admin"
  post 'whitelabel/update', to: "control_panel#white_label_update"
  post 'control_panel/user_update', to: "control_panel#user_update"

  root to: 'welcome#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :user
	belongs_to :partner
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	skip_before_action :verify_authenticity_token

	layout :set_layout

	def set_layout
		"layouts/application"

		partner = Partner.find_by(token: params[:bpid]) if params[:bpid]

		if (current_user.present? && current_user.account.partner.present? && current_user.account.partner.partner_type_id == 2) || (partner.present? && partner.partner_type_id == 2)
		  "layouts/blank"
		end
	end

	def whitelabel_login

	end

	def whitelabel_create_user_session
		pid = params[:pid]
		user = User.find_by(email: params[:user][:email])

		if user.present? && user.valid_password?(params[:user][:password]) == true
			flash[:info] = "Welcome back!"
			sign_in_and_redirect(user, params)
		else
			flash[:error] = "Uh-oh! You entered an invalid email or password."
			redirect_to "/app/partner/login?bpid=#{pid}"
		end

	end

	def whitelabel_update_account
		if current_user.valid_password?(params[:user][:current_password])
			if current_user.update_with_password({
					current_password: "#{params[:user][:current_password]}",
					password: "#{params[:user][:password]}",
					password_confirmation: "#{params[:user][:password_confirmation]}"
				})
				sign_in(current_user, :bypass => true)
				flash[:info] = "Your account changes have been saved."
				redirect_to controller: :welcome, action: :index
			else
				flash[:error] = "Hmmmm. We weren't able to update your password. Please try again."
				redirect_to "whitelabel_edit_account"
			end
		else
			flash[:error] = "Uh-oh! You entered an invalid email or password"
			redirect_to "whitelabel_edit_account"
		end
	end

	def whitelabel_logout
		pid = current_user.account.partner.token
		sign_out(current_user)

		redirect_to "/app/partner/login?bpid=#{pid}"
	end

	def notification_processor(processor, trans, email, name, pwd, user_id, processor_id, subscription_id, partner_id)
		trans = trans.upcase
		case trans
			when "SALE"
				acct_status = "approved"
			when "JV_SALE"
				acct_status = "approved"
			when "TEST_SALE"
				acct_status = "approved"
			when "TEST_JV_SALE"
				acct_status = "approved"
			when "RFND"
				acct_status = "frozen"
			when "TEST_RFND"
				acct_status = "frozen"
			when "CANCEL-REBILL"
				acct_status = "cancelled"
			when "UNCANCEL-REBILL"
				acct_status = "cancelled"
			when "CGBK"
				acct_status = "frozen"
		end

		if trans == "SALE" || trans == "JV_SALE" || trans == "TEST_SALE" || trans == "TEST_JV_SALE"


			unless name.blank?
				acct = Account.where(user_id: user_id).first
				acct.customer_name = name
				acct.payment_processor = processor
				acct.status = acct_status
				unless processor_id.blank?
					acct.processor_id = processor_id
				end
				unless subscription_id.blank?
					acct.subscription_id = subscription_id
				end
				unless partner_id.blank?
					acct.partner_id = partner_id
				end
				acct.save
			end

			#File.open("#{Rails.root}/log/credentials.log", "a") do |f|
			#	f.write("Name: #{name}\n")
			#	f.write("email: #{email}\n")
			#	f.write("password: #{pwd}\n")
			#	f.write("\n")
			#end

			#AccountMailer.jv_join_welcome(email, pwd).deliver
		else
			usr = User.find_by(email: email)
			acct = Account.find_by(user_id: usr.id)
			acct.status = acct_status
			acct.save
		end
		#render :nothing => true
	end

	def jvzoo_instant_notification
		#render :text => "Kindle Trend echo.", :status => 200, :content_type => 'text/html'
		
		logger.info "Received POST from JVZoo."
		ccustname = params[:ccustname]
		logger.info "ccustname = #{ccustname}."
		#ccuststate = params[:ccuststate]
		#ccustcc = params[:ccustcc]
		ccustemail = params[:ccustemail]
		logger.info "ccustemail = #{ccustemail}."
		#cproditem = params[:cproditem]
		#cprodtitle = params[:cprodtitle]
		#cprodtype = params[:cprodtype]
		ctransaction = params[:ctransaction]
		logger.info "ctransaction = #{ctransaction}."
		#ctransaffiliate = params[:ctransaffiliate]
		#ctransamount = params[:ctransamount]
		#ctranspaymentmethod = params[:ctranspaymentmethod]
		#ctransvendor = params[:ctransvendor]
		#ctransreceipt = params[:ctransreceipt]
		#cupsellreceipt = params[:cupsellreceipt]
		#caffitid = params[:caffitid]
		#cvendthru = params[:cvendthru]
		#cverify = params[:cverify]
		#ctranstime = params[:ctranstime]

		# Trans types: SALE, BILL, RFND, CGBK, INSF, CANCEL-REBILL, UNCANCEL-REBILL
		pwd = SecureRandom.hex(8)

		# Spawn a new User object...
		usr = User.new
		usr.password = pwd
		usr.password_confirmation = pwd
		usr.email = ccustemail
		usr.save

		# processor, trans, email, name, pwd, user_id, processor_id, subscription_id, partner_id
		#User.create!({:email => "#{ccustemail}", :password => "#{pwd}", :password_confirmation => "#{pwd}" })
		notification_processor("jvzoo", "#{ctransaction}", "#{ccustemail}", "#{ccustname}", "#{pwd}", usr.id, nil, nil, nil)

		@email = ccustemail
		@password = pwd

		AccountMailer.jv_join_welcome(ccustemail, pwd).deliver

		# Build a response string.
		params_str = ""
		params.each do |p|
			params_str.concat("#{p} | ")
		end

		params_str.concat("6Pa0wh3qjq3_f_4")

		respond_to do |format|
			#format.html {render :jvzoo_instant_notification, :layout => false}
			format.html do
				logger.info "Returning #{params_str}"
				render text: params_str
			end
		end
		#head 200, :content_type => 'text/html'
		#render :html => layout: false, :status => 200
	end

	def clickbank_instant_notification
		#caccountamount = params[:caccountamount]
		#ccurrency = params[:ccurrency]
		#ccustaddr1 = params[:ccustaddr1]
		#ccustaddr2 = params[:ccustaddr2]
		#ccustcc = params[:ccustcc]
		#ccustcity = params[:ccustcity]
		#ccustcounty = params[:ccustcounty]
		ccustemail = params[:ccustemail]
		#ccustfirstname = params[:ccustfirstname]
		ccustfullname = params[:ccustfullname]
		#ccustlastname = params[:ccustlastname]
		#ccustshippingcountry = params[:ccustshippingcountry]
		#ccustshippingzip = params[:ccustshippingzip]
		#ccuststate = params[:ccuststate]
		#ccustzip = params[:ccustzip]
		#cfuturepayments = params[:cfuturepayments]
		#cnextpaymentdate = params[:cnextpaymentdate]
		#corderamount = params[:corderamount]
		#cprocessedpayments = params[:cprocessedpayments]
		#cproditem = params[:cproditem]
		#cprodtitle = params[:cprodtitle]
		#cprodtype = params[:cprodtype]
		#crebillamnt = params[:crebillamnt]
		#crebillstatus = params[:crebillstatus]
		#ctid = params[:ctid]
		ctransaction = params[:ctransaction]
		#ctransaffiliate = params[:ctransaffiliate]
		#ctranspaymentmethod = params[:ctranspaymentmethod]
		#ctranspublisher = params[:ctranspublisher]
		#ctransreceipt = params[:ctransreceipt]
		#ctransrole = params[:ctransrole]
		#ctranstime = params[:ctranstime]
		#cupsellreceipt = params[:cupsellreceipt]
		#cvendthru = params[:cvendthru]
		#cverify = params[:cverify]
		#ccustshippingstate = params[:ccustshippingstate]
		#cnoticeversion = params[:cnoticeversion]
		#ctransvendor = params[:ctransvendor]
		#crebillfrequency = params[:crebillfrequency]
		#cbfid = params[:cbfid]
		#cbf = params[:cbf]
		#cbfpath = params[:cbfpath]
		#corderlanguage = params[:corderlanguage]
		#ctaxamount = params[:ctaxamount]
		#cshippingamount = params[:cshippingamount]

		# Trans types = SALE, JV_SALE, INSF, RFND, CGBK, BILL, JV_BILL, TEST_SALE, TEST_JV_SALE, TEST_BILL, TEST_JV_BILL, TEST_RFND

		# Spawn a new User object...
		usr = User.new
		usr.password = pwd
		usr.password_confirmation = pwd
		usr.email = ccustemail
		usr.save

		# processor, trans, email, name, pwd
		#User.create!({:email => "#{ccustemail}", :password => "#{pwd}", :password_confirmation => "#{pwd}" })
		notification_processor("clickbank", "#{ctransaction}", "#{ccustemail}", "#{ccustname}", "#{pwd}", usr.id, nil, nil, nil)

		@email = ccustemail
		@password = pwd

		AccountMailer.jv_join_welcome(email, pwd).deliver

		render :nothing => true
	end

	def paypal_instant_notification

		render :nothing => true
	end

	def click2sell_instant_notification
		ccustname = params[:buyer_name] + " " + params[:buyer_surname]
		#ccuststate = params[:ccuststate]
		#ccustcc = params[:ccustcc]
		ccustemail = params[:buyer_email]
		#cproditem = params[:cproditem]
		#cprodtitle = params[:cprodtitle]
		#cprodtype = params[:cprodtype]
		ctransaction = params[:transaction_type]
		#ctransaffiliate = params[:ctransaffiliate]
		#ctransamount = params[:ctransamount]
		#ctranspaymentmethod = params[:ctranspaymentmethod]
		#ctransvendor = params[:ctransvendor]
		#ctransreceipt = params[:ctransreceipt]
		#cupsellreceipt = params[:cupsellreceipt]
		#caffitid = params[:caffitid]
		#cvendthru = params[:cvendthru]
		#cverify = params[:cverify]
		#ctranstime = params[:ctranstime]

		# Trans types: Sale, Refund, Subscription, Chargeback
		pwd = SecureRandom.hex(8)

		# Spawn a new User object...
		usr = User.new
		usr.password = pwd
		usr.password_confirmation = pwd
		usr.email = ccustemail
		usr.save

		# processor, trans, email, name, pwd
		#User.create!({:email => "#{ccustemail}", :password => "#{pwd}", :password_confirmation => "#{pwd}" })
		notification_processor("click2sell", "#{ctransaction}", "#{ccustemail}", "#{ccustname}", "#{pwd}", usr.id, nil, nil, nil)
		@email = ccustemail
		@password = pwd

		AccountMailer.jv_join_welcome(email, pwd).deliver

		respond_to do |format|
			format.html {render :jvzoo_instant_notification, :layout => false}
		end
		#render :nothing => true
		#render :html => layout: false
	end

	def spawn_user
	usr_token = Hash.new

	unless params[:email].blank?
		unless User.find_by(email: "#{params[:email]}").nil?
			pwd = SecureRandom.hex(8)

			usr = User.new
			usr.password = pwd
			usr.password_confirmation = pwd
			usr.email = params[:email]
			usr.save

			usr_token["token"] = usr.account.token
		else
			usr_token["token"] = "existing_user"
		end
	else
		usr_token["token"] = "params_failure"
	end

	render json: usr_token
	end

	def partner_integration
		# params.each do |p|
		# 	puts "Param: #{p[0]} : #{p[1]}"
		# end
		#logger.info "PID: #{params[:pid]}"

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/instant_notification.html.erb
Params:
<%= @url %>

app/views/accounts/jvzoo_instant_notification.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
	</head>
	<body>
		<p>Welcome to Kindle Trend!</p>

		<p>Kindle Trend gives you the tools to not just see how your preferred niche is served, but to explore how many books are available in the many, many other underserved niches, equipping you to find profitable parallels.</p>

		<p>To get started, visit <a href="https://www.kindletrend.com/app" target="_BLANK">https://www.kindletrend.com/app</a>, and login with the following credentials:<br/>
		<strong>email:</strong> <%= @email %><br/>
		<strong>password:</strong> <%= @password %><br/><br/>
		We suggest that you change your password after you login for the first time. You can do so by clicking the "Edit Profile" link, located next to your email address on the right side of the Kindle Trend menu bar.</p>

		<p>Thanks for joining Kindle Trend! If you have any questions or comments, please use our <a href="http://www.kindletrend.com/contact-us/" target="_BLANK">contact form</a> and let us know!</p>

		<p>You're awesome!</p>

		<p>Sincerely,</p>
		The Kindle Trend Team
	</body>
</html>

app/views/accounts/whitelabel_edit_account.html.erb
<h1>Whitelabel edit account</h1>

<% if user_signed_in? %>
    <% if current_user.account.partner.present? && current_user.account.partner.app_style != nil %>
        <%= stylesheet_link_tag "bootstrap.#{current_user.account.partner.app_style}.min" %>
    <% end %>
<% end %>
<div class="container">
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title">Edit User</div>
                    </div>

                    <div style="padding-top:30px" class="panel-body" >

                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                        <form action="user/update" method="post" id="update_user_form">
                        <%#= devise_error_messages! %>
                            <div class="form-group">
                                <div style="margin-bottom: 25px" class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    <input autofocus="autofocus" class="form-control" id="user_email" name="user[email]" placeholder="email" type="email" value="<%= current_user.email %>" />
                                </div>
                            </div>

                            <div class="form-group">
                                <div style="margin-bottom: 25px" class="input-group">
                                  <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                    <input class="form-control" id="user_password" name="user[password]" placeholder="password" type="password" />
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <div style="margin-bottom: 25px" class="input-group">
                                  <span class="input-group-addon"><i class="glyphicon glyphicon-repeat"></i></span>
                                    <input class="form-control" id="user_password_confirmation" name="user[password_confirmation]" placeholder="confirm password" type="password" />
                                </div>
                            </div>

                            <div class="form-group">
                                 <div style="margin-bottom: 25px" class="input-group">
                                  <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                    <input class="form-control" id="user_current_password" name="user[current_password]" placeholder="current password (to confirm your changes)" type="password" />
                                </div>
                            </div>

                                <div style="margin:10px 0 0 0;" class="form-group">
                                    <!-- Button -->

                                    <div class="col-sm-12 controls">
                                      <input class="btn btn-success" name="save_bttn" id="save_bttn" type="submit" value="Update my account" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-12 control" style="margin-top: 10px;">
                                        <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                            Nevermind. Please take me
                      <%= link_to "back to the application.", root_path %><br />
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
        </div>
    </div>

<% case current_user.account.payment_processor %>
<% when "braintree" %>
    <div class="container">
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-info" >
                <div class="panel-heading">
                    <div class="panel-title">Cancel My Account</div>
                </div>
                <div style="padding-top:30px" class="panel-body" >
                    <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                    <div style="margin-bottom: 25px" class="input-group">
                      <p>If you wish to cancel your subscription to <strong><%= @friendly_product %></strong> for any reason, please click the button below. Note that doing so will PERMANENTLY DELETE your account, and you will no longer have access to <%= @friendly_product %> and its associated data, reports, and tools.</p>
                      <p>You will no longer be charged for your <%= @friendly_product %> subscription, starting at the next billing cycle.</p>
                    </div>
                    
                    <div style="margin:10px 0 0 0;" class="form-group">
                        <!-- Button -->
                        <div class="col-sm-12 controls">
                          <%#= button_to "PERMANENTLY DELETE my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger", :method => :delete %>
                          <%= button_to "PERMANENTLY DELETE my account", cancel_subscription_path(current_user), :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger", :method => :delete %>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12 control" style="margin-top: 10px;">
                            <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                I DO NOT wish to cancel, please
          <%= link_to "take me back to #{@friendly_product}.", root_path %><br />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% when "jvzoo" %>
<div class="container">
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info" >
            <div class="panel-heading">
                <div class="panel-title">Cancel My Account</div>
            </div>
            <div style="padding-top:30px" class="panel-body">
            <div style="margin-bottom: 25px" class="input-group">
                      <p>If you wish to cancel your subscription to <strong><%= @friendly_product %></strong> for any reason, please follow the instructions below. Note that doing so will PERMANENTLY DELETE your account, and you will no longer have access to <%= @friendly_product %> and its associated data, reports, and tools.</p>
                      <p>You will no longer be charged for your <%= @friendly_product %> subscription, starting at the next billing cycle.</p>
                    </div>
                <h4>To cancel your subscription from JVZoo:</h4>
                <ol>
                    <li>Log in to your <a href="https://www.paypal.com" target="_BLANK">PayPal account</a>.</li>
                    <li>Click <strong>Profile</strong> near the top of the page.</li>
                    <li>Click <strong>My money</strong>.</li>
                    <li>Click <strong>Update</strong> in the <strong>My preapproved payments</strong> section.</li>
                    <li>Click <strong>Cancel</strong>, <strong>Cancel automatic billing</strong>, or <strong>Cancel subscription</strong> and follow the instructions.</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<% else %>
    <div class="container">
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-info" >
                <div class="panel-heading">
                    <div class="panel-title">Cancel My Account</div>
                </div>
                <div style="padding-top:30px" class="panel-body" >
                    <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                    <div style="margin-bottom: 25px" class="input-group">
                      <p>If you wish to cancel your subscription to <strong><%= @friendly_product %></strong> for any reason, please click the button below to email they system administrators. Note that doing so will PERMANENTLY DELETE your account, and you will no longer have access to <%= @friendly_product %> and its associated data, reports, and tools.</p>
                      <p>You will no longer be charged for your <%= @friendly_product %> subscription, starting at the next billing cycle.</p>
                    </div>
                    
                    <% if current_user.account.partner.present? %>
                    <div style="margin:10px 0 0 0;" class="form-group">
                        <!-- Button -->
                        <div class="col-sm-12 controls">
                          <%#= button_to "PERMANENTLY DELETE my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger", :method => :delete %>
                          <%= link_to "PERMANENTLY DELETE my account", "mailto:#{current_user.account.partner.support_email}?subject=#{@friendly_product} - Please cancel my subscription", :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger", :target => "blank" %>
                        </div>
                    </div>
                    <% end %>

                    <div class="form-group">
                        <div class="col-md-12 control" style="margin-top: 10px;">
                            <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                I DO NOT wish to cancel, please
          <%= link_to "take me back to #{@friendly_product}.", root_path %><br />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

<script>
    $(function(){
        $("#update_user_form").bootstrapValidator({
            live: 'enabled',
            submitButtons: '#save_bttn',
            message: 'This value is not valid',
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },

            fields: {
                email: {
                    selector: "#user_email",
                    validators: {
                        notEmpty: {
                            message: 'A valid email address is required'
                        },
                        emailAddress: {
                            message: 'The input is not a valid email address'
                        }
                    }
                },

                password: {
                    selector: "#user_password",
                    validators: {
                        notEmpty: {
                                message: 'Please provide a new password for your Kindle Trend account'
                        },
                        stringLength: {
                                min: 8,
                                max: 100,
                                message: 'Your new password must be at least 8 characters long.'
                        },
                        identical: {
                            field: 'confirm_password',
                            message: 'The password and its confirmation are not the same'
                        }
                    }
                },

                confirm_password: {
                    selector: "#user_password_confirmation",
                    validators: {
                        notEmpty: {
                                message: 'Please confirm your password for your Kindle Trend account'
                        },
                        identical: {
                            field: 'password',
                            message: 'The password and its confirmation are not the same'
                        }
                    }
                },

                current_password: {
                    selector: "#user_current_password",
                    validators: {
                        notEmpty: {
                                message: 'Please provide a password for your Kindle Trend account'
                        },
                        stringLength: {
                                min: 8,
                                max: 100,
                                message: 'Your password must be at least 8 characters long.'
                        }
                    }
                }
            }
        });
    });
</script>

app/views/accounts/whitelabel_login.html.erb
<h1><%= @friendly_product %> login</h1>

<% if params[:bpid].present? %>
    <% partner = Partner.find_by(token: params[:bpid])
        if partner.app_style != nil %>
            <%= stylesheet_link_tag "bootstrap.#{partner.app_style}.min" %>
    <% end %>
<% end %>

<div class="container">
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title">Sign In</div>
                        <div style="float:right; font-size: 80%; position: relative; top:-10px"><%= link_to "Forgot your password?", "mailto:#{partner.support_email}?subject=Forgot password for #{partner.product_name}" %></div>
                    </div>

                    <div style="padding-top:30px" class="panel-body" >

                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                        <form accept-charset="UTF-8" action="/app/partner/user/login" class="new_user" id="new_user" method="post">

                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                        <input type="hidden" name="pid" id="pid" value="<%= partner.token || params[:bpid] %>" />
                                        <input autofocus="autofocus" class="form-control" id="user_email" name="user[email]" placeholder="email" type="email" value="" />
                                    </div>

                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                        <input class="form-control" id="user_password" name="user[password]" placeholder="password" type="password" />
                                    </div>

                                <div style="margin:10px 0 50px 0;" class="form-group">
                                    <!-- Button -->

                                    <div class="col-sm-12 controls">
                                      <input class="btn btn-success" name="commit" type="submit" value="Sign in" />
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
        </div>
    </div>